#!/usr/bin/env node
import { readdir, readFile, mkdir, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
const root=process.cwd(),src=path.join(root,'schemas/src'),files=(await readdir(src)).filter(v=>v.endsWith('.json')).sort(),schemas=[];
function canonical(value){if(Array.isArray(value))return value.map(canonical);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(key=>[key,canonical(value[key])]));return value;}
for(const file of files){const value=JSON.parse(await readFile(path.join(src,file),'utf8'));schemas.push({file,id:value.$id,sha256:createHash('sha256').update(JSON.stringify(canonical(value))).digest('hex')});}
const ts=`// Generated by schemas/generate.mjs; do not edit.\nexport const schemaRegistry = ${JSON.stringify(schemas,null,2)} as const;\nexport type ActionKey = 'idle'|'run'|'jump'|'fall'|'dash'|'attack_01'|'attack_02'|'attack_03'|'hit'|'death';\nexport interface TimeBase { numerator: 1; denominator: 30000 }\n`;
const rust=`// Generated by schemas/generate.mjs; do not edit.\npub const SCHEMA_REGISTRY: &[(&str,&str)] = &[${schemas.map(v=>`("${v.id}","${v.sha256}")`).join(',')}];\n`;
const golden=canonical({schemaVersion:'1.0.0',actionKeys:['idle','run','jump','fall','dash','attack_01','attack_02','attack_03','hit','death'],timeBase:{numerator:1,denominator:30000},registry:schemas});
const adversarial={vectors:[{id:'unknown-top-level-evidence',expected:'FAIL'},{id:'attack-alias-attack_1',expected:'FAIL'},{id:'nan-number',expected:'FAIL'},{id:'negative-revision',expected:'FAIL'},{id:'external-without-blocker',expected:'FAIL'}]};
for(const dir of ['schemas/generated/ts','schemas/generated/rust','schemas/generated/golden'])await mkdir(path.join(root,dir),{recursive:true});await writeFile(path.join(root,'schemas/generated/ts/index.ts'),ts);await writeFile(path.join(root,'schemas/generated/rust/mod.rs'),rust);await writeFile(path.join(root,'schemas/generated/golden/canonical.json'),JSON.stringify(golden)+'\n');await writeFile(path.join(root,'schemas/generated/golden/adversarial.json'),JSON.stringify(adversarial,null,2)+'\n');process.stdout.write(JSON.stringify({status:'PASS',schemas:schemas.length,registry:schemas},null,2)+'\n');
